# Generated by Django 5.1.3 on 2024-11-15 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('sport_type', models.CharField(choices=[('Football', 'Football'), ('Basketball', 'Basketball'), ('Tennis', 'Tennis'), ('Cricket', 'Cricket')], max_length=50)),
                ('available_time', models.TimeField()),
                ('booking_status', models.BooleanField(default=True)),
            ],
        ),
    ]
